### ISSUE TITLE
Config menu issue

### ISSUE THREAD

**Issue by jesuisfrog** [reonZ/pf2e-dailies#70] opened 2024-06-22 04:22 UTC
The config menu does not disable features that are unchecked and it will reset to having everything checked. Wanted to disable rations and familiar but it did not, had to set familiar abilities to 0 to prevent it from appearing.

**Comment by jesuisfrog** [comment] 2024-06-22 04:25
Issue seems to be on the GM side, when a player unchecks features, it works.

**Comment by reonZ** [comment] 2024-06-23 08:49
I can't reproduce the issue

https://github.com/reonZ/pf2e-dailies/assets/651462/c39937be-9ee1-470e-8e8c-bb41450951c5

**Comment by reonZ** [comment] 2024-06-28 13:08
I am closing this issue since no more news were given.

**Closed by reonZ** 2024-06-28 13:08 UTC

**Comment by TiltedWatcher** [comment] 2024-07-28 20:33
I'm experiencing the same issue.

The config menu doesn't save any changes made, defaulting to everything being active after closing it.

![2024-07-28_22-29-12 1](https://github.com/user-attachments/assets/13a321da-5c24-4240-b07a-19c3a94c84df)

That's on Foundry v11.315, using Pathfinder 2nd Edition v5.16.1, hosting the game on ForgeVTT.
